<a href="https://colab.research.google.com/github/BalkisG77/pythoncode-tutorials/blob/master/credit_model_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#importer les packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import pickle

In [3]:
#Lire la base de données 
df=pd.read_csv('/train_u6lujuX_CVtuZ9i.csv')
df

      Loan_ID  Gender Married  ... Credit_History Property_Area Loan_Status
0    LP001002    Male      No  ...            1.0         Urban           Y
1    LP001003    Male     Yes  ...            1.0         Rural           N
2    LP001005    Male     Yes  ...            1.0         Urban           Y
3    LP001006    Male     Yes  ...            1.0         Urban           Y
4    LP001008    Male      No  ...            1.0         Urban           Y
..        ...     ...     ...  ...            ...           ...         ...
609  LP002978  Female      No  ...            1.0         Rural           Y
610  LP002979    Male     Yes  ...            1.0         Rural           Y
611  LP002983    Male     Yes  ...            1.0         Urban           Y
612  LP002984    Male     Yes  ...            1.0         Urban           Y
613  LP002990  Female      No  ...            0.0     Semiurban           N

[614 rows x 13 columns]

In [5]:
pd.set_option('display.max_rows',df.shape[0]+1)

In [6]:
df

      Loan_ID  Gender Married  ... Credit_History Property_Area Loan_Status
0    LP001002    Male      No  ...            1.0         Urban           Y
1    LP001003    Male     Yes  ...            1.0         Rural           N
2    LP001005    Male     Yes  ...            1.0         Urban           Y
3    LP001006    Male     Yes  ...            1.0         Urban           Y
4    LP001008    Male      No  ...            1.0         Urban           Y
5    LP001011    Male     Yes  ...            1.0         Urban           Y
6    LP001013    Male     Yes  ...            1.0         Urban           Y
7    LP001014    Male     Yes  ...            0.0     Semiurban           N
8    LP001018    Male     Yes  ...            1.0         Urban           Y
9    LP001020    Male     Yes  ...            1.0     Semiurban           N
10   LP001024    Male     Yes  ...            1.0         Urban           Y
11   LP001027    Male     Yes  ...            1.0         Urban           Y
12   LP001028    Male     Yes  ...            1.0         Urban           Y
13   LP001029    Male      No  ...            1.0         Rural           N
14   LP001030    Male     Yes  ...            1.0         Urban           Y
15   LP001032    Male      No  ...            1.0         Urban           Y
16   LP001034    Male      No  ...            NaN         Urban           Y
17   LP001036  Female      No  ...            0.0         Urban           N
18   LP001038    Male     Yes  ...            1.0         Rural           N
19   LP001041    Male     Yes  ...            1.0         Urban           Y
20   LP001043    Male     Yes  ...            0.0         Urban           N
21   LP001046    Male     Yes  ...            1.0         Urban           Y
22   LP001047    Male     Yes  ...            0.0     Semiurban           N
23   LP001050     NaN     Yes  ...            0.0         Rural           N
24   LP001052    Male     Yes  ...            NaN     Semiurban           N
25   LP001066    Male     Yes  ...            1.0     Semiurban           Y
26   LP001068    Male     Yes  ...            1.0     Semiurban           Y
27   LP001073    Male     Yes  ...            1.0         Urban           Y
28   LP001086    Male      No  ...            1.0         Urban           N
29   LP001087  Female      No  ...            1.0     Semiurban           Y
30   LP001091    Male     Yes  ...            NaN         Urban           N
31   LP001095    Male      No  ...            1.0         Urban           N
32   LP001097    Male      No  ...            1.0         Rural           N
33   LP001098    Male     Yes  ...            1.0     Semiurban           Y
34   LP001100    Male      No  ...            1.0         Rural           N
35   LP001106    Male     Yes  ...            1.0         Urban           Y
36   LP001109    Male     Yes  ...            0.0         Urban           N
37   LP001112  Female     Yes  ...            1.0     Semiurban           Y
38   LP001114    Male      No  ...            1.0         Urban           Y
39   LP001116    Male      No  ...            1.0     Semiurban           Y
40   LP001119    Male      No  ...            1.0         Urban           N
41   LP001120    Male      No  ...            1.0         Urban           Y
42   LP001123    Male     Yes  ...            NaN         Urban           Y
43   LP001131    Male     Yes  ...            1.0     Semiurban           Y
44   LP001136    Male     Yes  ...            1.0         Urban           Y
45   LP001137  Female      No  ...            1.0         Urban           Y
46   LP001138    Male     Yes  ...            1.0         Urban           Y
47   LP001144    Male     Yes  ...            1.0         Urban           Y
48   LP001146  Female     Yes  ...            0.0         Urban           N
49   LP001151  Female      No  ...            1.0     Semiurban           Y
50   LP001155  Female     Yes  ...            1.0     Semiurban           Y
51   LP001157  Female      No  ...            1.0     Semiurban           Y
52   LP001164  Female      No  ...            1.0     Semiurban           N
53   LP001179    Male     Yes  ...            1.0         Urban           N
54   LP001186  Female     Yes  ...            0.0         Urban           N
55   LP001194    Male     Yes  ...            1.0     Semiurban           Y
56   LP001195    Male     Yes  ...            1.0     Semiurban           Y
57   LP001197    Male     Yes  ...            1.0         Rural           N
58   LP001198    Male     Yes  ...            1.0         Urban           Y
59   LP001199    Male     Yes  ...            1.0         Urban           Y
60   LP001205    Male     Yes  ...            1.0         Urban           Y
61   LP001206    Male     Yes  ...            1.0         Urban           Y
62   LP001207    Male     Yes  ...            0.0         Rural           N
63   LP001213    Male     Yes  ...            0.0         Rural           N
64   LP001222  Female      No  ...            0.0     Semiurban           N
65   LP001225    Male     Yes  ...            1.0     Semiurban           N
66   LP001228    Male      No  ...            0.0         Urban           N
67   LP001233    Male     Yes  ...            1.0         Urban           Y
68   LP001238    Male     Yes  ...            1.0         Urban           Y
69   LP001241  Female      No  ...            0.0     Semiurban           N
70   LP001243    Male     Yes  ...            1.0         Urban           Y
71   LP001245    Male     Yes  ...            1.0     Semiurban           Y
72   LP001248    Male      No  ...            1.0     Semiurban           Y
73   LP001250    Male     Yes  ...            0.0     Semiurban           N
74   LP001253    Male     Yes  ...            1.0     Semiurban           Y
75   LP001255    Male      No  ...            1.0         Urban           N
76   LP001256    Male      No  ...            1.0         Urban           N
77   LP001259    Male     Yes  ...            1.0         Urban           N
78   LP001263    Male     Yes  ...            0.0     Semiurban           N
79   LP001264    Male     Yes  ...            NaN     Semiurban           Y
80   LP001265  Female      No  ...            1.0     Semiurban           Y
81   LP001266    Male     Yes  ...            1.0     Semiurban           Y
82   LP001267  Female     Yes  ...            1.0         Urban           N
83   LP001273    Male     Yes  ...            NaN     Semiurban           N
84   LP001275    Male     Yes  ...            1.0         Urban           Y
85   LP001279    Male      No  ...            1.0     Semiurban           Y
86   LP001280    Male     Yes  ...            NaN     Semiurban           Y
87   LP001282    Male     Yes  ...            1.0     Semiurban           Y
88   LP001289    Male      No  ...            1.0         Urban           Y
89   LP001310    Male     Yes  ...            1.0     Semiurban           Y
90   LP001316    Male     Yes  ...            1.0     Semiurban           Y
91   LP001318    Male     Yes  ...            1.0     Semiurban           Y
92   LP001319    Male     Yes  ...            1.0         Urban           Y
93   LP001322    Male      No  ...            1.0     Semiurban           Y
94   LP001325    Male      No  ...            1.0     Semiurban           Y
95   LP001326    Male      No  ...            NaN         Urban           N
96   LP001327  Female     Yes  ...            1.0     Semiurban           Y
97   LP001333    Male     Yes  ...            1.0     Semiurban           Y
98   LP001334    Male     Yes  ...            1.0     Semiurban           Y
99   LP001343    Male     Yes  ...            1.0     Semiurban           Y
100  LP001345    Male     Yes  ...            1.0         Urban           Y
101  LP001349    Male      No  ...            1.0     Semiurban           Y
102  LP001350    Male     Yes  ...            1.0         Urban           Y
103  LP001356    Male     Yes  ...            1.0     Semiurban           Y
104  LP001357    Male     NaN  ...            1.0         Urban           Y
105  LP001367    Male     Yes  ...            1.0         Urban           Y
106  LP001369    Male     Yes  ...            1.0         Urban           Y
107  LP001370    Male      No  ...            1.0         Rural           N
108  LP001379    Male     Yes  ...            0.0         Urban           N
109  LP001384    Male     Yes  ...            1.0     Semiurban           Y
110  LP001385    Male      No  ...            1.0         Urban           Y
111  LP001387  Female     Yes  ...            1.0     Semiurban           Y
112  LP001391    Male     Yes  ...            0.0         Rural           N
113  LP001392  Female      No  ...            1.0     Semiurban           Y
114  LP001398    Male      No  ...            1.0     Semiurban           Y
115  LP001401    Male     Yes  ...            1.0         Rural           Y
116  LP001404  Female     Yes  ...            1.0     Semiurban           Y
117  LP001405    Male     Yes  ...            NaN         Urban           Y
118  LP001421    Male     Yes  ...            1.0         Rural           N
119  LP001422  Female      No  ...            1.0         Urban           Y
120  LP001426    Male     Yes  ...            1.0         Rural           Y
121  LP001430  Female      No  ...            1.0     Semiurban           Y
122  LP001431  Female      No  ...            0.0     Semiurban           Y
123  LP001432    Male     Yes  ...            1.0     Semiurban           Y
124  LP001439    Male     Yes  ...            1.0         Rural           Y
125  LP001443  Female      No  ...            NaN         Rural           Y
126  LP001448     NaN     Yes  ...            1.0         Rural           Y
127  LP001449    Male      No  ...            1.0         Rural           Y
128  LP001451    Male     Yes  ...            0.0         Urban           N
129  LP001465    Male     Yes  ...            NaN         Rural           N
130  LP001469    Male      No  ...            NaN         Urban           Y
131  LP001473    Male      No  ...            1.0         Urban           Y
132  LP001478    Male      No  ...            1.0     Semiurban           Y
133  LP001482    Male     Yes  ...            1.0     Semiurban           Y
134  LP001487    Male      No  ...            1.0     Semiurban           Y
135  LP001488    Male     Yes  ...            1.0     Semiurban           N
136  LP001489  Female     Yes  ...            1.0         Rural           N
137  LP001491    Male     Yes  ...            1.0         Urban           Y
138  LP001492    Male      No  ...            0.0     Semiurban           N
139  LP001493    Male     Yes  ...            1.0         Rural           N
140  LP001497    Male     Yes  ...            1.0         Rural           N
141  LP001498    Male      No  ...            1.0         Urban           Y
142  LP001504    Male      No  ...            1.0     Semiurban           Y
143  LP001507    Male     Yes  ...            1.0     Semiurban           Y
144  LP001508    Male     Yes  ...            1.0         Urban           Y
145  LP001514  Female     Yes  ...            1.0     Semiurban           Y
146  LP001516  Female     Yes  ...            1.0         Urban           Y
147  LP001518    Male     Yes  ...            1.0         Urban           Y
148  LP001519  Female      No  ...            1.0         Rural           N
149  LP001520    Male     Yes  ...            1.0     Semiurban           Y
150  LP001528    Male      No  ...            0.0         Rural           N
151  LP001529    Male     Yes  ...            1.0         Rural           Y
152  LP001531    Male      No  ...            1.0         Urban           N
153  LP001532    Male     Yes  ...            1.0         Rural           N
154  LP001535    Male      No  ...            1.0         Urban           Y
155  LP001536    Male     Yes  ...            0.0     Semiurban           Y
156  LP001541    Male     Yes  ...            NaN         Rural           Y
157  LP001543    Male     Yes  ...            1.0         Urban           Y
158  LP001546    Male      No  ...            1.0         Rural           Y
159  LP001552    Male     Yes  ...            1.0     Semiurban           Y
160  LP001560    Male     Yes  ...            1.0     Semiurban           Y
161  LP001562    Male     Yes  ...            1.0         Urban           N
162  LP001565    Male     Yes  ...            0.0     Semiurban           N
163  LP001570    Male     Yes  ...            1.0         Rural           Y
164  LP001572    Male     Yes  ...            1.0         Urban           Y
165  LP001574    Male     Yes  ...            1.0         Rural           Y
166  LP001577  Female     Yes  ...            1.0         Rural           N
167  LP001578    Male     Yes  ...            1.0         Rural           Y
168  LP001579    Male      No  ...            0.0     Semiurban           N
169  LP001580    Male     Yes  ...            1.0     Semiurban           Y
170  LP001581    Male     Yes  ...            1.0         Rural           Y
171  LP001585     NaN     Yes  ...            1.0         Urban           Y
172  LP001586    Male     Yes  ...            1.0         Rural           N
173  LP001594    Male     Yes  ...            1.0     Semiurban           Y
174  LP001603    Male     Yes  ...            1.0     Semiurban           N
175  LP001606    Male     Yes  ...            1.0         Rural           Y
176  LP001608    Male     Yes  ...            1.0         Rural           Y
177  LP001610    Male     Yes  ...            0.0     Semiurban           N
178  LP001616    Male     Yes  ...            1.0     Semiurban           Y
179  LP001630    Male      No  ...            0.0         Urban           N
180  LP001633    Male     Yes  ...            0.0         Urban           N
181  LP001634    Male      No  ...            NaN         Rural           N
182  LP001636    Male     Yes  ...            1.0     Semiurban           Y
183  LP001637    Male     Yes  ...            1.0     Semiurban           N
184  LP001639  Female     Yes  ...            1.0     Semiurban           Y
185  LP001640    Male     Yes  ...            1.0     Semiurban           Y
186  LP001641    Male     Yes  ...            0.0         Rural           N
187  LP001643    Male     Yes  ...            NaN         Rural           Y
188  LP001644     NaN     Yes  ...            1.0         Rural           Y
189  LP001647    Male     Yes  ...            1.0         Rural           Y
190  LP001653    Male      No  ...            1.0         Rural           Y
191  LP001656    Male      No  ...            1.0     Semiurban           N
192  LP001657    Male     Yes  ...            1.0         Urban           N
193  LP001658    Male      No  ...            1.0     Semiurban           Y
194  LP001664    Male      No  ...            1.0         Rural           Y
195  LP001665    Male     Yes  ...            1.0     Semiurban           N
196  LP001666    Male      No  ...            1.0         Rural           Y
197  LP001669  Female      No  ...            1.0         Urban           Y
198  LP001671  Female     Yes  ...            NaN     Semiurban           Y
199  LP001673    Male      No  ...            1.0         Urban           N
200  LP001674    Male     Yes  ...            1.0     Semiurban           Y
201  LP001677    Male      No  ...            0.0     Semiurban           Y
202  LP001682    Male     Yes  ...            1.0         Urban           N
203  LP001688    Male     Yes  ...            1.0         Urban           Y
204  LP001691    Male     Yes  ...            1.0     Semiurban           Y
205  LP001692  Female      No  ...            1.0     Semiurban           Y
206  LP001693  Female      No  ...            1.0         Urban           Y
207  LP001698    Male      No  ...            1.0         Rural           Y
208  LP001699    Male      No  ...            1.0         Urban           Y
209  LP001702    Male      No  ...            1.0     Semiurban           N
210  LP001708  Female      No  ...            1.0     Semiurban           N
211  LP001711    Male     Yes  ...            0.0     Semiurban           N
212  LP001713    Male     Yes  ...            1.0         Urban           Y
213  LP001715    Male     Yes  ...            1.0         Rural           Y
214  LP001716    Male     Yes  ...            1.0         Urban           Y
215  LP001720    Male     Yes  ...            1.0     Semiurban           Y
216  LP001722    Male     Yes  ...            1.0         Rural           N
217  LP001726    Male     Yes  ...            1.0     Semiurban           Y
218  LP001732    Male     Yes  ...            0.0     Semiurban           N
219  LP001734  Female     Yes  ...            NaN     Semiurban           Y
220  LP001736    Male     Yes  ...            0.0         Urban           N
221  LP001743    Male     Yes  ...            1.0     Semiurban           Y
222  LP001744    Male      No  ...            1.0     Semiurban           Y
223  LP001749    Male     Yes  ...            1.0     Semiurban           Y
224  LP001750    Male     Yes  ...            1.0     Semiurban           Y
225  LP001751    Male     Yes  ...            1.0         Rural           N
226  LP001754    Male     Yes  ...            1.0         Urban           N
227  LP001758    Male     Yes  ...            1.0     Semiurban           Y
228  LP001760    Male     NaN  ...            1.0     Semiurban           Y
229  LP001761    Male      No  ...            1.0         Rural           Y
230  LP001765    Male     Yes  ...            1.0     Semiurban           Y
231  LP001768    Male     Yes  ...            1.0         Rural           Y
232  LP001770    Male      No  ...            1.0         Rural           Y
233  LP001776  Female      No  ...            1.0     Semiurban           Y
234  LP001778    Male     Yes  ...            1.0     Semiurban           Y
235  LP001784    Male     Yes  ...            1.0         Rural           Y
236  LP001786    Male     Yes  ...            NaN         Urban           N
237  LP001788  Female      No  ...            NaN         Urban           Y
238  LP001790  Female      No  ...            1.0         Rural           Y
239  LP001792    Male     Yes  ...            1.0     Semiurban           Y
240  LP001798    Male     Yes  ...            1.0         Rural           Y
241  LP001800    Male     Yes  ...            1.0         Urban           N
242  LP001806    Male      No  ...            1.0         Urban           Y
243  LP001807    Male     Yes  ...            1.0         Rural           Y
244  LP001811    Male     Yes  ...            1.0     Semiurban           Y
245  LP001813    Male      No  ...            1.0         Urban           N
246  LP001814    Male     Yes  ...            1.0         Urban           Y
247  LP001819    Male     Yes  ...            1.0         Urban           Y
248  LP001824    Male     Yes  ...            1.0     Semiurban           Y
249  LP001825    Male     Yes  ...            1.0         Urban           Y
250  LP001835    Male     Yes  ...            0.0     Semiurban           N
251  LP001836  Female      No  ...            1.0         Urban           N
252  LP001841    Male      No  ...            1.0         Rural           Y
253  LP001843    Male     Yes  ...            1.0     Semiurban           Y
254  LP001844    Male      No  ...            0.0         Urban           N
255  LP001846  Female      No  ...            1.0         Rural           Y
256  LP001849    Male      No  ...            0.0         Rural           N
257  LP001854    Male     Yes  ...            1.0         Urban           N
258  LP001859    Male     Yes  ...            1.0         Rural           N
259  LP001864    Male     Yes  ...            NaN     Semiurban           N
260  LP001865    Male     Yes  ...            NaN         Urban           Y
261  LP001868    Male      No  ...            1.0     Semiurban           Y

In [9]:
pd.set_option('display.max_rows',10)
df

      Loan_ID  Gender Married  ... Credit_History Property_Area Loan_Status
0    LP001002    Male      No  ...            1.0         Urban           Y
1    LP001003    Male     Yes  ...            1.0         Rural           N
2    LP001005    Male     Yes  ...            1.0         Urban           Y
3    LP001006    Male     Yes  ...            1.0         Urban           Y
4    LP001008    Male      No  ...            1.0         Urban           Y
..        ...     ...     ...  ...            ...           ...         ...
609  LP002978  Female      No  ...            1.0         Rural           Y
610  LP002979    Male     Yes  ...            1.0         Rural           Y
611  LP002983    Male     Yes  ...            1.0         Urban           Y
612  LP002984    Male     Yes  ...            1.0         Urban           Y
613  LP002990  Female      No  ...            0.0     Semiurban           N

[614 rows x 13 columns]

In [10]:
#Voir les valeurs manquantes 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [11]:
df.isnull().sum().sort_values(ascending=False)

Credit_History       50
Self_Employed        32
LoanAmount           22
Dependents           15
Loan_Amount_Term     14
                     ..
Property_Area         0
CoapplicantIncome     0
ApplicantIncome       0
Education             0
Loan_ID               0
Length: 13, dtype: int64

In [66]:
#Valeurs statistiques 
df.describe()

       ApplicantIncome  CoapplicantIncome  ...  Loan_Amount_Term  Credit_History
count       614.000000         614.000000  ...         600.00000      564.000000
mean       5403.459283        1621.245798  ...         342.00000        0.842199
std        6109.041673        2926.248369  ...          65.12041        0.364878
min         150.000000           0.000000  ...          12.00000        0.000000
25%        2877.500000           0.000000  ...         360.00000        1.000000
50%        3812.500000        1188.500000  ...         360.00000        1.000000
75%        5795.000000        2297.250000  ...         360.00000        1.000000
max       81000.000000       41667.000000  ...         480.00000        1.000000

[8 rows x 5 columns]

In [67]:
#df.describe(include='0')

In [68]:
#renseigner les valeurs manquantes 
cat_data = []
num_data = []
for i,c in enumerate(df.dtypes):
  if c==object:
    cat_data.append(df.iloc[:,i])
  else:
    num_data.append(df.iloc[:,i])
cat_data=pd.DataFrame(cat_data).transpose()
num_data=pd.DataFrame(num_data).transpose()
num_data

     ApplicantIncome  CoapplicantIncome  ...  Loan_Amount_Term  Credit_History
0             5849.0                0.0  ...             360.0             1.0
1             4583.0             1508.0  ...             360.0             1.0
2             3000.0                0.0  ...             360.0             1.0
3             2583.0             2358.0  ...             360.0             1.0
4             6000.0                0.0  ...             360.0             1.0
..               ...                ...  ...               ...             ...
609           2900.0                0.0  ...             360.0             1.0
610           4106.0                0.0  ...             180.0             1.0
611           8072.0              240.0  ...             360.0             1.0
612           7583.0                0.0  ...             360.0             1.0
613           4583.0                0.0  ...             360.0             0.0

[614 rows x 5 columns]

In [69]:
df.dtypes

Loan_ID              object
Gender               object
Married              object
Dependents           object
Education            object
                     ...
LoanAmount          float64
Loan_Amount_Term    float64
Credit_History      float64
Property_Area        object
Loan_Status          object
Length: 13, dtype: object

In [70]:
#Pour les variables catégoriques on va remplacer les valeurs manquantes par
cat_data=cat_data.apply(lambda x:x.fillna(x.value_counts().index[0]))
cat_data.isnull().sum().any()

False

In [71]:
cat_data['Married'].value_counts()

Yes    401
No     213
Name: Married, dtype: int64

In [72]:
num_data.fillna(method='bfill',inplace=True)
num_data.isnull().sum().any()

False

In [73]:
num_data

     ApplicantIncome  CoapplicantIncome  ...  Loan_Amount_Term  Credit_History
0             5849.0                0.0  ...             360.0             1.0
1             4583.0             1508.0  ...             360.0             1.0
2             3000.0                0.0  ...             360.0             1.0
3             2583.0             2358.0  ...             360.0             1.0
4             6000.0                0.0  ...             360.0             1.0
..               ...                ...  ...               ...             ...
609           2900.0                0.0  ...             360.0             1.0
610           4106.0                0.0  ...             180.0             1.0
611           8072.0              240.0  ...             360.0             1.0
612           7583.0                0.0  ...             360.0             1.0
613           4583.0                0.0  ...             360.0             0.0

[614 rows x 5 columns]

In [ ]:
#Changer les valeurs  avec la variable target y 0 et 1

In [74]:
#Transformer la colonne target 
target_value={'Y':1,'N':0}
target=cat_data['Loan_Status']
cat_data.drop('Loan_Status', axis=1, inplace=True)
target=target.map(target_value)
target

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int64

In [76]:
#remplacer les valeurs catégoriques par des valeurs numériques 0 et 1 
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat_data:
  cat_data[i]=le.fit_transform(cat_data[i])
cat_data

     Loan_ID  Gender  Married  ...  Education  Self_Employed  Property_Area
0          0       1        0  ...          0              0              2
1          1       1        1  ...          0              0              0
2          2       1        1  ...          0              1              2
3          3       1        1  ...          1              0              2
4          4       1        0  ...          0              0              2
..       ...     ...      ...  ...        ...            ...            ...
609      609       0        0  ...          0              0              0
610      610       1        1  ...          0              0              0
611      611       1        1  ...          0              0              2
612      612       1        1  ...          0              0              2
613      613       0        0  ...          0              1              1

[614 rows x 7 columns]

In [77]:
#Supprimer loan id 
cat_data.drop('Loan_ID', axis=1,inplace=True)

In [78]:
#concatenante les deux cata et num data 
X=pd.concat([cat_data,num_data], axis=1)
y=target

In [79]:
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int64